app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /

api:
    resource: '@ApiBundle/Controller/'
    type: rest
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc